server:
  port: 8083
  max-http-request-header-size: 20000 # Desde Apisix llega un header muy grande
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
spring:
  application:
    name: blog-service
  cache:
    type: SIMPLE
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/blog_service
    driverClassName: com.mysql.cj.jdbc.Driver
    username: blog
    password: test
  jpa: 
    hibernate:
      ddl-auto: update
  security: 
    oauth2: 
      resourceserver:  
        jwt:  
          issuer-uri: http://localhost:9000/realms/blog
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          token-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token
          revoke-token-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/logout
          client-secret: qBRU1VYkKAFSOQkm95zASFe0HFmfCmfZ
jwt:  
  auth:  
    converter: 
      resource-id: blog-client
      principal-attribute: principal_username
max-comments-per-hour: 22
max-comments-per-post: 2