version: "3"

services:

  keycloak:    
    image: quay.io/keycloak/keycloak:latest  
    command: start-dev --proxy edge
    environment:     
      KC_HTTP_PORT: 9000 
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_svr
      KC_DB_URL_DATABASE: db_name
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: user_name
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: passthrough
      KC_PROXY_ADDRESS_FORWARDING: "true"
    ports:      
      - "9000:9000"      
    depends_on:      
      postgres_svr:
        condition: service_healthy

  postgres_svr: 
    image: postgres:latest
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'    
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
